//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackwardChainingMVVM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackwardChainingMVVM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrównoważony.
        /// </summary>
        internal static string Balanced {
            get {
                return ResourceManager.GetString("Balanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekstrawertyczny.
        /// </summary>
        internal static string Extravert {
            get {
                return ResourceManager.GetString("Extravert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wybrano hipotezy..
        /// </summary>
        internal static string HypothesisIsNotSelected {
            get {
                return ResourceManager.GetString("HypothesisIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introwertyczny.
        /// </summary>
        internal static string Introvert {
            get {
                return ResourceManager.GetString("Introvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mieszany.
        /// </summary>
        internal static string Mixed {
            get {
                return ResourceManager.GetString("Mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neurotyczny.
        /// </summary>
        internal static string Neurotic {
            get {
                return ResourceManager.GetString("Neurotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nie.
        /// </summary>
        internal static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik ma zrównoważony temperament.
        /// </summary>
        internal static string UserIsBalanced {
            get {
                return ResourceManager.GetString("UserIsBalanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik jest ekstrawertykiem.
        /// </summary>
        internal static string UserIsExtrovert {
            get {
                return ResourceManager.GetString("UserIsExtrovert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik jest introwertykiem.
        /// </summary>
        internal static string UserIsIntrovert {
            get {
                return ResourceManager.GetString("UserIsIntrovert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik jest melancholikiem.
        /// </summary>
        internal static string UserIsMelancholic {
            get {
                return ResourceManager.GetString("UserIsMelancholic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik ma mieszany temperament.
        /// </summary>
        internal static string UserIsMixed {
            get {
                return ResourceManager.GetString("UserIsMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik jest neurotykiem.
        /// </summary>
        internal static string UserIsNeurotic {
            get {
                return ResourceManager.GetString("UserIsNeurotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik nie ma zrównoważonego temperamentu.
        /// </summary>
        internal static string UserIsNotBalanced {
            get {
                return ResourceManager.GetString("UserIsNotBalanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik nie jest ekstrawertykiem.
        /// </summary>
        internal static string UserIsNotExtrovert {
            get {
                return ResourceManager.GetString("UserIsNotExtrovert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik nie jest introwertykiem.
        /// </summary>
        internal static string UserIsNotIntrovert {
            get {
                return ResourceManager.GetString("UserIsNotIntrovert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik nie jest melancholikiem.
        /// </summary>
        internal static string UserIsNotMelancholic {
            get {
                return ResourceManager.GetString("UserIsNotMelancholic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik nie ma mieszanego temperamentu.
        /// </summary>
        internal static string UserIsNotMixed {
            get {
                return ResourceManager.GetString("UserIsNotMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik nie jest neurotykiem.
        /// </summary>
        internal static string UserIsNotNeurotic {
            get {
                return ResourceManager.GetString("UserIsNotNeurotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik nie jest flegmatykiem.
        /// </summary>
        internal static string UserIsNotPhlegmatic {
            get {
                return ResourceManager.GetString("UserIsNotPhlegmatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik nie jest sangwinikiem.
        /// </summary>
        internal static string UserIsNotSanguine {
            get {
                return ResourceManager.GetString("UserIsNotSanguine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik nie jest cholerykiem.
        /// </summary>
        internal static string UserIsNotSpitfire {
            get {
                return ResourceManager.GetString("UserIsNotSpitfire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik jest flegmatykiem.
        /// </summary>
        internal static string UserIsPhlegmatic {
            get {
                return ResourceManager.GetString("UserIsPhlegmatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik jest sangwinikiem.
        /// </summary>
        internal static string UserIsSanguine {
            get {
                return ResourceManager.GetString("UserIsSanguine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik jest cholerykiem.
        /// </summary>
        internal static string UserIsSpitfire {
            get {
                return ResourceManager.GetString("UserIsSpitfire", resourceCulture);
            }
        }
    }
}
